//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Chizhonok
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demoChizhonokEntities : DbContext
    {
        public demoChizhonokEntities()
            : base("name=demoChizhonokEntities")
        {
        }

        private static demoChizhonokEntities _Context;

        public static demoChizhonokEntities getContext()
        {
            if (_Context == null)
                _Context = new demoChizhonokEntities();
            return _Context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<storage> storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
